### ISSUE TITLE
incorrect line in package.json

### ISSUE THREAD

**Issue by a16bitsysop** [SequentMicrosystems/8mosind-rpi#1]
https://github.com/SequentMicrosystems/8mosind-rpi/blob/27082494f2e191b4e5acce88aefbad843bc10506/node-red-contrib-sm-8mosind/package.json#L18

this should be `8mosind` not `relay`, also after changing this the dialog in node-red has `Relay Number` should this be `Mosfet Number`?

**Comment by a16bitsysop** [comment]
the makefile has incorrect `root.root` instead of `root:root` for chown as well

**Comment by alexburcea2877** [comment]
Thank you, we will fix it asap.
