### ISSUE TITLE
Values read/written-to in Python do not match real life

### ISSUE THREAD

**Issue by Poofjunior** [SequentMicrosystems/8mosind-rpi#3]
It looks like the values read from Python do not match the values in real life.

**Board**: Eight Mosfets Hat V3.1, configured as address 0.
**lib8mosind version:** 1.0.1 (according to `pip freeze` and installed with `sudo pip install SM8mosind`)
**Setup:** Mosfets 1-4 and 7 are connected to valves (with flyback diodes). Mosfets 5, 6, and 8 are not connected to anything.
**External State**: all LEDs (1 through 8) are **off** in real life. All valves are deenergized. Device (and valve PSU) was hard reset.

```python
>>> lib8mosind.get(0, 5)
1
>>> lib8mosind.get(0, 6)
0
>>> lib8mosind.get(0, 7)
1
>>> lib8mosind.get(0, 8)
1
>>> bin(lib8mosind.get_all(0))
'0b11010000'
```
In the above text editor, the values read from the board, should be all zeros.

Additionally, calling
```python
>>> lib8mosind.set(0, 1, 1)
````
causes LEDs (and their corresponding outputs) 1 **and** 5, 7, and 8 to turn on.

**Comment by Poofjunior** [comment]
Solved. It looks like the *Eight Mosfets* Hat and *Sixteen LV Digital Inputs* Hat share an address range. Switching the Eight Mosfets board to address "1" fixes the problem.

This isn't super obvious, and it could be beneficial to highlight the address collision on either product page.

From the [Eight Mosftets Hat](https://sequentmicrosystems.com/products/eight-mosfets-8-layer-stackable-card-for-raspberry-pi?srsltid=AfmBOoonQf954OH4sYMQQfShIOFGISuMW-zJbfENmxLmjyuxYY4_4L97) page:

> Uses only I2C port (address 0x20..0x27 or 0x38..0x3f ), all GPIO pins available

From the [16 LV Digital Inputs manual, pg 7](https://cdn.shopify.com/s/files/1/0534/4392/0067/files/16-INPUTS-UsersGuide_fe9f7d34-7077-4415-af79-57fdae1e534f.pdf?v=1704912646)
![image](https://github.com/user-attachments/assets/d75ccc92-196c-41fc-b0ff-e1795e28a2ff)

**Comment by alexburcea2877** [comment]
Sorry for the late reply and I am glad you solved it.

Alex.
